force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Object used to assign an user to a stage of a project with a defined number of days to consume.</description>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{YYYY}-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <formula>ProjectStage__r.ProjectName__r.Name</formula>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/ProjectStage__c.field-meta.xml
<CustomField>
    <fullName>ProjectStage__c</fullName>
    <label>Project Stage</label>
    <referenceTo>Project_Stage__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Stage__c/Project_Stage__c.object-meta.xml
<CustomObject>
    <label>Project Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Stage__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Projet__c</referenceTo>
    <relationshipLabel>Project Stages</relationshipLabel>
    <relationshipName>ProjectStages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>External id {YYYYMMdd-UserId}</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/MondayDate__c.field-meta.xml
<CustomField>
    <fullName>MondayDate__c</fullName>
    <label>Monday Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#DDDDDD</color>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
                <color>#FFFF66</color>
                <label>Submitted For Approval</label>
            </value>
            <value>
                <fullName>Must be updated</fullName>
                <color>#FF9900</color>
                <label>Must be updated</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <color>#33FF33</color>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/TECH_RunApproval__c.field-meta.xml
<CustomField>
    <fullName>TECH_RunApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RunApproval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/TimesheetEntry__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TSE-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimesheetEntry__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <description>Each Assignment must be affected to an assignment</description>
    <label>Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>TimesheetEntries_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/MondayDate__c.field-meta.xml
<CustomField>
    <fullName>MondayDate__c</fullName>
    <description>Date of Monday of the Timesheet&#39;s week</description>
    <label>Monday Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/ProjectStage__c.field-meta.xml
<CustomField>
    <fullName>ProjectStage__c</fullName>
    <formula>Assignment__r.ProjectStage__r.Name</formula>
    <label>Project stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of TSE</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <description>Relationship between TSE and TS.</description>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>TimesheetEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Moon_TimesheetsContainer_LC.cls
public without sharing class Moon_TimesheetsContainer_LC {

  @AuraEnabled 
  public static TimeSheetsDetailsWrapper getTimeSheetsDetailsWrapper() {
    Moon_TimesheetDomain oTimesheetDomain = new Moon_TimesheetDomain() ; 

    return new TimeSheetsDetailsWrapper(oTimesheetDomain) ; 
  }

  @AuraEnabled 
  public static List<Assignment__c> getAssignements(String sDate) {
    System.debug('getAssignement >> '+sDate) ; 
    Moon_TimesheetDomain oTimesheetDomain = new Moon_TimesheetDomain() ; 

    String[] arrDate = sDate.split('-') ; 
    Date dCurrentWeek = Date.newInstance(Integer.valueOf(arrDate[0]) ,Integer.valueOf(arrDate[1]) ,Integer.valueOf(arrDate[2]) ) ; 

    return oTimesheetDomain.getAssignements(dCurrentWeek) ;
  }
  
  @AuraEnabled 
  public static TimeSheetsDetailsWrapper getTimeSheetsDetailsWrapper(String sDate) {
    Moon_TimesheetDomain oTimesheetDomain = new Moon_TimesheetDomain() ; 

    return new TimeSheetsDetailsWrapper(oTimesheetDomain) ; 
  }

  @AuraEnabled 
  public static Map<String,Object> saveTimesheetsEntries(String sTSEntries,List<String> lTSToDelete,Boolean runApproval) {

    List<Object> lRawTSEntries = (List<Object>)JSON.deserializeUntyped(sTSEntries) ;
    Date dCurrentWeek = null ; 
    String sTimesheetExternalId = null ; 
    System.Debug('aha lRawTSEntries !'+lRawTSEntries) ; 
    System.Debug('aha lTSToDelete !'+lTSToDelete) ; 
    List<TimesheetEntry__c> lTSEntries =new  List<TimesheetEntry__c>() ; 
    for(Object oTSEntry : lRawTSEntries){  
      Map<String,Object> mapTSEntry = (Map<String,Object>)oTSEntry ; 
 

      if(mapTSEntry.containsKey('Assignment__r')){
        mapTSEntry.remove('Assignment__r')  ;
        System.debug('mapTSEntry > '+mapTSEntry );
      }  
      for(String key :mapTSEntry.keySet()){
        System.debug(key) ;
      }
      String sDate = (String)mapTSEntry.get('MondayDate__c') ; 
      String[] arrDate = sDate.split('-') ; 
      sTimesheetExternalId = arrDate[0]+arrDate[1]+arrDate[2]+'-'+UserInfo.getUserid() ;
      dCurrentWeek = Date.newInstance(Integer.valueOf(arrDate[0]) ,Integer.valueOf(arrDate[1]) ,Integer.valueOf(arrDate[2]) ) ; 
      mapTSEntry.put('Mondaydate__c',dCurrentWeek)  ;
      if((String)mapTSEntry.get('Status__c')!='Accepted')
        lTSEntries.add((TimesheetEntry__c)JSON.deserialize( JSON.serialize(mapTSEntry),TimesheetEntry__c.class) ) ;
    }

    System.Debug('aha lTSEntries !'+lTSEntries) ; 

    System.Debug('aha dCurrentWeek !'+dCurrentWeek) ; 

    Boolean isSuccess = true ; 
    String sMessage ='Saved.' ; 
    List<TimesheetEntry__c> lNewTSEntries = new List<TimesheetEntry__c> () ; 
    {
        try{
          Database.upsert(lTSEntries,TimesheetEntry__c.ExternalId__c) ; 
          if(lTSToDelete!=null && lTSToDelete.size()>0){
            List<TimesheetEntry__c> lTSEntriesToDelete =new  List<TimesheetEntry__c>() ; 
            for(String idTSEntry : lTSToDelete){
              lTSEntriesToDelete.add(new TimesheetEntry__c(Id=idTSEntry,ExternalId__c=idTSEntry+'-DELETED-'+Datetime.now()) ) ; 
            }
            Database.update(lTSEntriesToDelete) ; 
            Database.delete(lTSToDelete) ; 

          }
          //Update ts entries
          if(dCurrentWeek!=null){
            if(runApproval && sTimesheetExternalId != null){
             upsert new Timesheet__c(ExternalId__c=sTimesheetExternalId, Status__c = Moon_TimesheetDomain.TIMESHEET_STATUT_APPROVAL,TECH_RunApproval__c = true  ) Timesheet__c.ExternalId__c ; 
            }
            Moon_TimesheetDomain oTimesheetDomain = new Moon_TimesheetDomain() ; 
            lNewTSEntries = oTimesheetDomain.getTimesheetEntriesWithRange(dCurrentWeek,0) ; 

          System.Debug('aha lNewTSEntries !'+lNewTSEntries) ;
          }
        }catch(System.DmlException e){
          System.debug('Error >'+e) ;
          System.debug('Error trace >'+e.getStackTraceString()) ;
          sMessage =e.getDmlMessage(0);
          isSuccess = false ;         
        }catch(Exception e){
          System.debug('Error >'+e) ;
          System.debug('Error trace >'+e.getStackTraceString()) ;
          sMessage =e+''+e.getStackTraceString() ; 
          isSuccess = false ; 
        }
    }
    return new Map<String,Object>{'isSuccess'=>isSuccess,'message'=>sMessage,'lTSEntries'=>lNewTSEntries } ; 
  }  

  public class TimeSheetsDetailsWrapper{

    @AuraEnabled 
    public Date dCurrentTSDate ; //YYYY-MM-dd
    
    @AuraEnabled 
    public String sCurrentWeekMonday ; //YYYY-MM-dd
    @AuraEnabled 
    public String sCurrentWeekNumber ; //44
    @AuraEnabled 
    public String sCurrentYear ; //2020
    @AuraEnabled 
    public String sWeekLabel ; //30 dec. to 3 jan.
    @AuraEnabled
    public List<Id> lOwnersIds ;  
    @AuraEnabled
    public String sMode ; // CAPTAIN / CREW

    @AuraEnabled
    public String sFullName ;
    @AuraEnabled
    public String sPhotoURL ;  

    @AuraEnabled
    public Map<String,List<TimesheetEntry__c>> mapWeekTSEntries = new Map<String,List<TimesheetEntry__c>>() ;  
    

    @AuraEnabled
    public Map<String,List<Assignment__c>> mapProjectAssignement = new Map<String,List<Assignment__c>>() ; 

    @AuraEnabled
    public Map<String,List<Assignment__c>> mapInternalAssignement = new Map<String,List<Assignment__c>>() ;

    //public TimeSheetsDetailsWrapper(){
    //  this.sCurrentWeekNumber = '44' ; 
    //  this.sCurrentYear = '2019' ; 
    //  this.sCurrentWeekMonday = '2019-12-27' ; 
    //  this.sWeekLabel = '30 dec. to 3 jan.' ; 
    //  this.lOwnersIds = new List<Id>{'0051v000004y5HJAAY'} ; 
    //  this.sMode = 'CREW' ; 
    //  User u = [SELECT FullPhotoUrl 
    //              FROM User 
    //              WHERE id=:Userinfo.getUserid()];
    //  this.sPhotoURL = u.FullPhotoUrl;
    //  this.sFullName = UserInfo.getFirstName()+' '+UserInfo.getLastName() ; 
    //}

    public TimeSheetsDetailsWrapper(Moon_TimesheetDomain oTimesheetDomain){
      this.dCurrentTSDate = oTimesheetDomain.getCurrentTSDate() ; 
      Datetime dttCurrentTS = Datetime.newInstance(this.dCurrentTSDate,Time.newInstance(12,0,0,0) ) ; 
      Datetime dttCurrentTSEndWeek = dttCurrentTS.addDays(4) ; 

      this.sCurrentWeekNumber = dttCurrentTS.format('w') ; 
      this.sCurrentWeekMonday = dttCurrentTS.format('YYYY-MM-dd')  ; 
      this.sCurrentYear = dttCurrentTS.format('YYYY-MM-dd')  ; 
      this.sWeekLabel = dttCurrentTS.day()+' '+dttCurrentTS.format('MMM')+'. to '+dttCurrentTSEndWeek.day()+' '+dttCurrentTSEndWeek.format('MMM')+'.' ; 
      this.lOwnersIds = oTimesheetDomain.lIdUsers   ; 
      this.sMode = (lOwnersIds.size()>1)? 'CAPTAIN' : 'CREW' ; 
      User u = [SELECT FullPhotoUrl 
                  FROM User 
                  WHERE id=:Userinfo.getUserid()];
      this.sPhotoURL = u.FullPhotoUrl;
      this.sFullName = UserInfo.getFirstName()+' '+UserInfo.getLastName() ;

      //Init timesheet entries
      System.debug('oTimesheetDomain.getTimesheetEntries size > '+oTimesheetDomain.getTimesheetEntries().size() )  ; 
      for(TimesheetEntry__c oTSEntry : oTimesheetDomain.getTimesheetEntries()){
        this.addTSEntry(oTSEntry) ; 
      }   

       for(Assignment__c oAssignement : oTimesheetDomain.getAssignements()){
          this.addAssignement(oAssignement);
       }  

    }

    public void addTSEntry(TimesheetEntry__c oTSEntry){
      
      List<TimesheetEntry__c> lTSEntries ; 
      String sDateKey = Moon_Timesheet_Util.converteToDateKey(oTSEntry.MondayDate__c) ;
      if(mapWeekTSEntries.containsKey(sDateKey)){
        lTSEntries = mapWeekTSEntries.get(sDateKey); 
      }else{        
        lTSEntries = new List<TimesheetEntry__c> (); 
        mapWeekTSEntries.put(sDateKey,lTSEntries) ;
      }

      lTSEntries.add(oTSEntry) ; 
    }

    public void addAssignement(Assignment__c oAssignement){

      Map<String,List<Assignment__c>> mapAssignement = (oAssignement.ProjectStage__r.ProjectName__r.Account__r.Name=='LEVANA')
                                                        ? mapInternalAssignement 
                                                        :  mapProjectAssignement ; 
      List<Assignment__c> lAssignements ; 
      if(mapAssignement.containsKey(oAssignement.ProjectName__c)){
        lAssignements = mapAssignement.get(oAssignement.ProjectName__c); 
      }else{        
        lAssignements = new List<Assignment__c>(); 
        mapAssignement.put(oAssignement.ProjectName__c,lAssignements) ;
      }

      lAssignements.add(oAssignement) ;       
    }


  }

  //public class TimesheetslinesWrapper{

  //  @AuraEnabled
  //  public String sOwnerName ; 

  //  @AuraEnabled
  //  public List<TimesheetEntry__c> lTSEntries ; 

  //  public TimesheetslinesWrapper(List<TimesheetEntry__c> lTimesheets,String sOwnerName){
  //    this.sOwnerName = sOwnerName ; 
  //    mWeekTimesheets = new Map<String,List<TimesheetEntry__c>>() ; 

  //    for(TimesheetEntry__c oTimesheet : lTimesheets){
  //      this.addTSEntry(oTimesheet) ; 
  //    }
  //  }
  //  public TimesheetslinesWrapper(String sOwnerName){
  //    this.sOwnerName = sOwnerName ; 
  //    mWeekTimesheets = new Map<String,List<TimesheetEntry__c>>() ; 
  //  }    

  //  public void addTSEntry(TimesheetEntry__c oTimesheet){
  //    String sDateKey = Moon_Timesheet_Util.converteToDateKey(oTimesheet.MondayDate__c) ;
  //    List<TimesheetEntry__c> lTimesheets ; 
  //    if(mWeekTimesheets.containsKey(sDateKey)){
  //      lTimesheets = mWeekTimesheets.get(sDateKey); 
  //    }else{        
  //      lTimesheets = new List<TimesheetEntry__c>(); 
  //      mWeekTimesheets.put(sDateKey,lTimesheets) ; 
  //    }
  //    lTimesheets.add(oTimesheet) ; 
  //  }

  //}




}