force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Object used to assign an user to a stage of a project with a defined number of days to consume.</description>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{YYYY}-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/AssignedUser__c.field-meta.xml
<CustomField>
    <fullName>AssignedUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/DailyCostPrice__c.field-meta.xml
<CustomField>
    <fullName>DailyCostPrice__c</fullName>
    <label>Daily Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <formula>ProjectStage__r.ProjectName__r.Name</formula>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/ProjectStage__c.field-meta.xml
<CustomField>
    <fullName>ProjectStage__c</fullName>
    <label>Project Stage</label>
    <referenceTo>Project_Stage__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Stage__c/Project_Stage__c.object-meta.xml
<CustomObject>
    <label>Project Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Stage__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Projet__c</referenceTo>
    <relationshipLabel>Project Stages</relationshipLabel>
    <relationshipName>ProjectStages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Stage__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Starting</fullName>
                <default>true</default>
                <label>Not Starting</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>External id {YYYYMMdd-UserId}</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/MondayDate__c.field-meta.xml
<CustomField>
    <fullName>MondayDate__c</fullName>
    <label>Monday Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#DDDDDD</color>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
                <color>#FFFF66</color>
                <label>Submitted For Approval</label>
            </value>
            <value>
                <fullName>Must be updated</fullName>
                <color>#FF9900</color>
                <label>Must be updated</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <color>#33FF33</color>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/TimesheetEntry__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TSE-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimesheetEntry__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User Assigned to this timesheet</description>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <description>Each Assignment must be affected to an assignment</description>
    <label>Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>TimesheetEntries_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/MondayDate__c.field-meta.xml
<CustomField>
    <fullName>MondayDate__c</fullName>
    <description>Date of Monday of the Timesheet&#39;s week</description>
    <label>Monday Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/ProjectStage__c.field-meta.xml
<CustomField>
    <fullName>ProjectStage__c</fullName>
    <formula>Assignment__r.ProjectStage__r.Name</formula>
    <label>Project stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of TSE</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <description>Relationship between TSE and TS.</description>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>TimesheetEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TESTDataFactory.cls
@isTest
public class TESTDataFactory {
  public static final Date MONDAY_DATE = Date.newInstance(2020,06,29) ;
  public static final String SMONDAY_DATE = '20200629' ;


  public static void initSetupData() {
    TESTDataFactory.initTSAndTSEntries(1,null,true) ; 
  }
  public static void initTSAndTSEntries(integer numAccount,String recordTypeDeveloperName,
                                              Boolean insertAndReturn)
  {
    Timesheet__c oNewTS = new Timesheet__c()  ; 
    oNewTS.put('MondayDate__c',TESTDataFactory.MONDAY_DATE) ; 
    oNewTS.put('ExternalId__c',TESTDataFactory.SMONDAY_DATE+'-'+UserInfo.getUserId()) ; 
    oNewTS.put('Status__c','Open') ; 
    insert oNewTS ; 

    List<Assignment__c> lAssignments = TESTDataFactory.insertAssignement(1,null,null,false) ; 
    insert lAssignments ; 

    TimesheetEntry__c oNewETS = new TimesheetEntry__c() ; 
    oNewETS.put('MondayDate__c',TESTDataFactory.MONDAY_DATE) ; 
    oNewETS.put('ExternalId__c',TESTDataFactory.SMONDAY_DATE+'-'+UserInfo.getUserId()+'-'+lAssignments[0].Id ) ; 
    oNewETS.put('Status__c','Draft') ; 
    oNewETS.put('Timesheet__c',oNewTS.Id) ; 
    oNewETS.put('Assignment__c',lAssignments[0].Id) ; 
    oNewETS.put('Assignee__c',UserInfo.getUserId()) ; 
    insert oNewETS ;          
  }
      //Return map of accounts fiels set for "Locataire" recordtype
   
  public static List<Assignment__c> insertAssignement(integer numAccount,String recordTypeDeveloperName,Map<String,object> mapFieldsValues,
                                              Boolean insertAndReturn)
    {
      if(mapFieldsValues==null){
          mapFieldsValues=TESTDataFactory.getAssignmentDefaultMapFields(); 
      } 
      if(!mapFieldsValues.containsKey('ProjectStage__c')){
          List<Project_Stage__c> lProjectsStages = TESTDataFactory.insertProjectStage(1,null,null,true) ; 
          mapFieldsValues.put('ProjectStage__c',lProjectsStages[0].Id) ;             
      }

      return insertSobject(numAccount,'Assignment__c',recordTypeDeveloperName,mapFieldsValues,insertAndReturn)  ;         
            
    }
      //Return map of accounts fiels set for "Locataire" recordtype
    public static Map<String,Object> getAssignmentDefaultMapFields(){
      Map<String,Object> mapFieldsValues=new Map<String,Object>() ;  
      //Initialise Opportunity fields
      //Create Locataire account
      List<Project_Stage__c> lProjectsStages = TESTDataFactory.insertProjectStage(1,null,null,false) ; 
      insert lProjectsStages ; 
      
      //Set related objects Id
      mapFieldsValues.put('ProjectStage__c',lProjectsStages[0].Id) ; 

      //Set opportunity fields
      mapFieldsValues.put('AssignedUser__c',UserInfo.getUserId()) ; 
      mapFieldsValues.put('DailyCostPrice__c',200) ;
      mapFieldsValues.put('StartDate__c',Date.Today()) ;       

      return mapFieldsValues ; 
    }    

 public static List<Project_Stage__c> insertProjectStage(integer numAccount,String recordTypeDeveloperName,Map<String,object> mapFieldsValues,
                                              Boolean insertAndReturn)
    {
      if(mapFieldsValues==null){
          mapFieldsValues=TESTDataFactory.getProjectStageDefaultMapFields(); 
      } 
      if(!mapFieldsValues.containsKey('ProjectName__c')){
          List<Projet__c> lProjects = TESTDataFactory.insertProject(1,null,null,true) ; 
          mapFieldsValues.put('ProjectName__c',lProjects[0].Id) ;             
      }
      if(!mapFieldsValues.containsKey('Name')){
           mapFieldsValues.put('Name','TESTPROJECTSTAGE') ;            
      }

      return insertSobject(numAccount,'Project_Stage__c',recordTypeDeveloperName,mapFieldsValues,insertAndReturn)  ;         
            
    }
      //Return map of accounts fiels set for "Locataire" recordtype
    public static Map<String,Object> getProjectStageDefaultMapFields(){
      Map<String,Object> mapFieldsValues=new Map<String,Object>() ;  
      //Initialise Opportunity fields
      //Create Locataire account
      List<Projet__c> lProjects = TESTDataFactory.insertProject(1,null,null,false) ; 
      insert lProjects ; 
      
      //Set related objects Id
      mapFieldsValues.put('ProjectName__c',lProjects[0].Id) ; 

      //Set opportunity fields
      mapFieldsValues.put('Name','TESTPROJECTSTAGE') ;
      mapFieldsValues.put('Statut__c','In Progress') ;       

      return mapFieldsValues ; 
    }        

    public static List<Projet__c> insertProject(integer numAccount,String recordTypeDeveloperName,Map<String,object> mapFieldsValues,
                                              Boolean insertAndReturn)
    {
      if(mapFieldsValues==null){
          mapFieldsValues=TESTDataFactory.getProjectDefaultMapFields(); 
      } 
      if(!mapFieldsValues.containsKey('Opportunite__c')){
          List<Opportunity> lOpportunities = TESTDataFactory.insertOpportunity(1,null,null,true) ; 
          mapFieldsValues.put('Opportunite__c',lOpportunities[0].Id) ;             
      }
      if(!mapFieldsValues.containsKey('Name')){
           mapFieldsValues.put('Name','TESTOPPORTUNITY') ;            
      }

      return insertSobject(numAccount,'Projet__c',recordTypeDeveloperName,mapFieldsValues,insertAndReturn)  ;         
            
    }
      //Return map of accounts fiels set for "Locataire" recordtype
    public static Map<String,Object> getProjectDefaultMapFields(){
      Map<String,Object> mapFieldsValues=new Map<String,Object>() ;  
      //Initialise Opportunity fields
      //Create Locataire account
      List<Opportunity> lOpportunities = TESTDataFactory.insertOpportunity(1,null,null,false) ; 
      insert lOpportunities ; 
      
      //Set related objects Id
      mapFieldsValues.put('Opportunite__c',lOpportunities[0].Id) ; 

      //Set opportunity fields
      mapFieldsValues.put('ModeFacturation__c','FixedTerms') ; 
      mapFieldsValues.put('Name',lOpportunities[0].Name) ;
      mapFieldsValues.put('Statut__c','In Progress') ;       

      return mapFieldsValues ; 
    }    

    public static List<Opportunity> insertOpportunity(integer numAccount,String recordTypeDeveloperName,Map<String,object> mapFieldsValues,
                                              Boolean insertAndReturn)
    {
      if(mapFieldsValues==null){
          mapFieldsValues=TESTDataFactory.getOpportunityDefaultMapFields(); 
      }
      if(!mapFieldsValues.containsKey('AccountId')){
          List<Account> lAccounts = TESTDataFactory.insertAccount(1,null,null,true) ; 
          mapFieldsValues.put('AccountId',lAccounts[0].Id) ;             
      }
      if(!mapFieldsValues.containsKey('Name')){
           mapFieldsValues.put('Name','TESTOPPORTUNITY') ;            
      }

      return insertSobject(numAccount,'Opportunity',recordTypeDeveloperName,mapFieldsValues,insertAndReturn)  ;         
            
    }
      //Return map of accounts fiels set for "Locataire" recordtype
    public static Map<String,Object> getOpportunityDefaultMapFields(){
      Map<String,Object> mapFieldsValues=new Map<String,Object>() ;  
      //Initialise Opportunity fields
      //Create Locataire account
      List<Account> lAccounts = TESTDataFactory.insertAccount(1,null,null,false) ; 
      insert lAccounts ; 
      
      //Set related objects Id
      mapFieldsValues.put('AccountId',lAccounts[0].Id) ; 

      //Set opportunity fields
      mapFieldsValues.put('closeDate',Date.Today()) ; 
      mapFieldsValues.put('Name',lAccounts[0].Name) ;
      mapFieldsValues.put('StageName','Qualification') ;       

      return mapFieldsValues ; 
    }

    public static List<Account> insertAccount (integer numAccount,String recordTypeDeveloperName,Map<String,object> mapFieldsValues,
                                                Boolean insertAndReturn)
      {
          if(mapFieldsValues==null){
              mapFieldsValues=TESTDataFactory.getAccountDefaultMapFields(); 
          }
          
          return insertSobject(numAccount,'Account',null,mapFieldsValues,insertAndReturn)  ;         
    }

    //Return map of accounts fiels set for "Locataire" recordtype
    public static Map<String,Object> getAccountDefaultMapFields(){
        Map<String,Object> mapFieldsValues=new Map<String,Object>() ;  
        //Initialise Account variables
        mapFieldsValues.put('Name','Moon & Cie') ; 
        mapFieldsValues.put('Type','Prospect') ; 
        return mapFieldsValues ; 
    }

    public static List<Sobject> insertSobject(Integer iCount,String sObjectName,String sRecordTypeDeveloperName,Map<String,object> mapFieldsValues,Boolean isInsertEnabled)
    {        
        
        List<sObject> lSobjectToInsert=new List<Sobject>() ;
        Set<String> uniqueFields = new Set<String>{'NAME','FIRSTNAME', 'LASTNAME', 'USERNAME', 'SURNAME', 'COMMUNITYNICKNAME'};
        

        //Set recordtype Id from RecordType Name
        if(sRecordTypeDeveloperName!=null){
            mapFieldsValues.put('RecordTypeId',
                Schema.getGlobalDescribe().get(sObjectName).getDescribe().getRecordTypeInfosByDeveloperName().get(sRecordTypeDeveloperName).getRecordTypeId());                  
        }

        for(Integer i=0;i<iCount;i++){
            //Id recordtypId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('recordType').getRecordTypeId();
            sObject dynObject= Schema.getGlobalDescribe().get(sObjectName).newSObject() ;
            if(mapFieldsValues!=null)
                for(String key : mapFieldsValues.keySet()){
                    if(uniqueFields.contains(key.toUpperCase())){  
                        String sSuffix=(i==0)?'':''+i ;                        
                        dynObject.put(key,mapFieldsValues.get(key)+sSuffix) ;
                        continue ;
                    }
                    dynObject.put(key,mapFieldsValues.get(key)) ;
                }
            lSobjectToInsert.add(dynObject) ;
        }

        if(isInsertEnabled)
            //try {
                insert lSobjectToInsert;
            //} catch (DmlException d) {
               // d.getMessage();
            //}
        return lSobjectToInsert ; 
    }
}