force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Object used to assign an user to a stage of a project with a defined number of days to consume.</description>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{YYYY}-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/AssignedUser__c.field-meta.xml
<CustomField>
    <fullName>AssignedUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>ProjectStage__r.Name + &#39;_&#39; +  AssignedUser__r.LastName + &#39;_&#39; +  TEXT(StartDate__c)</formula>
    <label>Assignment Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <formula>ProjectStage__r.ProjectName__r.Name</formula>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/ProjectStage__c.field-meta.xml
<CustomField>
    <fullName>ProjectStage__c</fullName>
    <label>Project Stage</label>
    <referenceTo>Project_Stage__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Stage__c/Project_Stage__c.object-meta.xml
<CustomObject>
    <label>Project Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Stage__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <label>Project Name</label>
    <referenceTo>Projet__c</referenceTo>
    <relationshipLabel>Project Stages</relationshipLabel>
    <relationshipName>ProjectStages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Stage__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Starting</fullName>
                <default>true</default>
                <label>Not Starting</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/FridayAM__c.field-meta.xml
<CustomField>
    <fullName>FridayAM__c</fullName>
    <label>Friday AM</label>
    <summarizedField>TimesheetEntry__c.FridayAM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/MondayAM__c.field-meta.xml
<CustomField>
    <fullName>MondayAM__c</fullName>
    <label>Monday AM</label>
    <summarizedField>TimesheetEntry__c.MondayAM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/MondayDate__c.field-meta.xml
<CustomField>
    <fullName>MondayDate__c</fullName>
    <label>Monday Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/MondayPM__c.field-meta.xml
<CustomField>
    <fullName>MondayPM__c</fullName>
    <label>Monday PM</label>
    <summarizedField>TimesheetEntry__c.MondayPM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#DDDDDD</color>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
                <color>#FFFF66</color>
                <label>Submitted For Approval</label>
            </value>
            <value>
                <fullName>Must be updated</fullName>
                <color>#FF9900</color>
                <label>Must be updated</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <color>#33FF33</color>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#FF0000</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/ThursdayAM__c.field-meta.xml
<CustomField>
    <fullName>ThursdayAM__c</fullName>
    <label>Thursday AM</label>
    <summarizedField>TimesheetEntry__c.ThursdayAM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/ThursdayPM__c.field-meta.xml
<CustomField>
    <fullName>ThursdayPM__c</fullName>
    <label>Thursday PM</label>
    <summarizedField>TimesheetEntry__c.ThursdayPM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/TuesdayAM__c.field-meta.xml
<CustomField>
    <fullName>TuesdayAM__c</fullName>
    <label>Tuesday AM</label>
    <summarizedField>TimesheetEntry__c.TuesdayAM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/TuesdayPM__c.field-meta.xml
<CustomField>
    <fullName>TuesdayPM__c</fullName>
    <label>Tuesday PM</label>
    <summarizedField>TimesheetEntry__c.TuesdayPM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/WednesdayAM__c.field-meta.xml
<CustomField>
    <fullName>WednesdayAM__c</fullName>
    <label>Wednesday AM</label>
    <summarizedField>TimesheetEntry__c.WednesdayAM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/WednesdayPM__c.field-meta.xml
<CustomField>
    <fullName>WednesdayPM__c</fullName>
    <label>Wednesday PM</label>
    <summarizedField>TimesheetEntry__c.WednesdayPM__c</summarizedField>
    <summaryForeignKey>TimesheetEntry__c.Timesheet__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/TimesheetEntry__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TSE-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimesheetEntry__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User Assigned to this timesheet</description>
    <label>Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheet_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <description>Each Assignment must be affected to an assignment</description>
    <label>Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>TimesheetEntries_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/MondayAM__c.field-meta.xml
<CustomField>
    <fullName>MondayAM__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Charge of morning Monday on the project associated to the assignment during the week of Timesheet.</description>
    <label>Monday AM</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/MondayDate__c.field-meta.xml
<CustomField>
    <fullName>MondayDate__c</fullName>
    <description>Date of Monday of the Timesheet&#39;s week</description>
    <label>Monday Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/MondayPM__c.field-meta.xml
<CustomField>
    <fullName>MondayPM__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Charge of afternoon Monday on the project associated to the assignment during the week of Timesheet.</description>
    <label>Monday PM</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/ProjectStage__c.field-meta.xml
<CustomField>
    <fullName>ProjectStage__c</fullName>
    <formula>Assignment__r.ProjectStage__r.Name</formula>
    <label>Project stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of TSE</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/ThursdayAM__c.field-meta.xml
<CustomField>
    <fullName>ThursdayAM__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Charge of morning Thusday on the project associated to the assignment during the week of Timesheet.</description>
    <label>Thursday AM</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/ThursdayPM__c.field-meta.xml
<CustomField>
    <fullName>ThursdayPM__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Charge of afternoon Thusday on the project associated to the assignment during the week of Timesheet.</description>
    <label>Thursday PM</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/TuesdayAM__c.field-meta.xml
<CustomField>
    <fullName>TuesdayAM__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Charge of morning Tuesday on the project associated to the assignment during the week of Timesheet.</description>
    <label>Tuesday AM</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/TuesdayPM__c.field-meta.xml
<CustomField>
    <fullName>TuesdayPM__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Charge of afternoon Tuesday on the project associated to the assignment during the week of Timesheet.</description>
    <label>Tuesday PM</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/WednesdayAM__c.field-meta.xml
<CustomField>
    <fullName>WednesdayAM__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Charge of morning wednesday on the project associated to the assignment during the week of Timesheet.</description>
    <label>Wednesday AM</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/WednesdayPM__c.field-meta.xml
<CustomField>
    <fullName>WednesdayPM__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Charge of afternoon Wednesday on the project associated to the assignment during the week of Timesheet.</description>
    <label>Wednesday PM</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Moon_TimesheetDomain.cls
public with sharing class Moon_TimesheetDomain {



    public static final Date TIMESHEET_STARTDATE_MANDATORY = Date.newInstance(2020,06,29) ; 
    
    public List<Id> lIdUsers {get;set;} 

    public static final String TIMESHEET_STATUT_OPEN = 'Open' ; 
    public static final String TIMESHEET_STATUT_TOBEUPDATED = 'Rejected' ; 
    public static final String TIMESHEET_STATUT_APPROVAL = 'Submitted For Approval' ; 
    public static final List<String> PROJECTSTAGE_STATUT_CLOSED = new List<String>{'Closed'} ; 

    private List<Assignment__c> lAssignements  ; 

    private Date dtCurrentTS  ;

    private List<TimesheetEntry__c> lTimesheetEntries  ;    

    public Moon_TimesheetDomain() {
        lIdUsers = new List<id>() ;
        String idUser = UserInfo.getUserId() ; 
        lIdUsers.add(idUser) ; 
    }

    public Moon_TimesheetDomain(Date dtCurrentTS) {
        this.dtCurrentTS= dtCurrentTS ; 
        lIdUsers = new List<id>() ;
        String idUser = UserInfo.getUserId() ; 
        lIdUsers.add(idUser) ; 
    }

    public Moon_TimesheetDomain(List<Id> lIdUsers) {
        this.lIdUsers = lIdUsers ;
    }

    public List<Assignment__c> getAssignements(){
      return getAssignements(this.getCurrentTSDate()) ; 
    }

    //sDAte
    public List<Assignment__c> getAssignements(Date dtDate){

      this.lAssignements = [SELECT Id, Name__c,ProjectName__c,Name,ProjectStage__r.ProjectName__c,StartDate__c, EndDate__c,
                                    ProjectStage__r.ProjectName__r.Account__r.Name,ProjectStage__r.Name,
                                    ProjectStage__r.Statut__c
                                  FROM Assignment__c 
                                  WHERE ProjectStage__r.Statut__c  NOT IN :Moon_TimesheetDomain.PROJECTSTAGE_STATUT_CLOSED
                                  AND AssignedUser__c IN :lIdUsers
                                  ORDER BY Name__c ASC ] ; 
      return this.lAssignements  ; 
    }

    public List<TimesheetEntry__c> getTimesheetEntries(){

      return this.getTimesheetEntries(this.getCurrentTSDate()) ; 
    }



    public List<TimesheetEntry__c> getTimesheetEntries(Date dtDate){
      return getTimesheetEntriesWithRange(dtDate,600)  ;                
    }
    public List<TimesheetEntry__c> getTimesheetEntriesWithRange(Date dtDate,Integer iRangeDays){
      Date dtMondeyDate = dtDate.toStartofWeek() ; 
      System.debug('dtMondeyDate - iRangeDays > '+(dtMondeyDate - iRangeDays)) ;
      System.debug('dtMondeyDate + iRangeDays > '+(dtMondeyDate + iRangeDays)) ;
      System.debug('lIdUsers > '+lIdUsers) ;
      lTimesheetEntries = [SELECT Id,MondayDate__c,Assignee__c, MondayAM__c, MondayPM__c, ThursdayAM__c, ThursdayPM__c,Status__c,
                             WednesdayAM__c, WednesdayPM__c, TuesdayAM__c, TuesdayPM__c, FridayAM__c, FridayPM__c,ExternalId__c,
                             Timesheet__r.Status__c,Assignee__r.Name,Assignment__r.ProjectStage__r.Name, Timesheet__r.Id
                             FROM TimesheetEntry__c
                             WHERE Assignee__c IN :lIdUsers
                             AND MondayDate__c >= :dtMondeyDate - iRangeDays
                             AND MondayDate__c <= :dtMondeyDate + iRangeDays 
                             ] ;
      return lTimesheetEntries ;                    
    }

    public Date getCurrentTSDate(){
      if(dtCurrentTS==null){      
          this.dtCurrentTS = Date.today().toStartofWeek() ; 
          List<Timesheet__c> lTimesheets = [SELECT Id, MondayDate__c 
                                            FROM Timesheet__c
                                            WHERE 
                                            ( Status__c = :Moon_TimesheetDomain.TIMESHEET_STATUT_OPEN
                                              OR 
                                            Status__c = :Moon_TimesheetDomain.TIMESHEET_STATUT_TOBEUPDATED
                                            )
                                            AND OwnerId IN :lIdUsers
                                            AND MondayDate__c!=null
                                            ORDER BY MondayDate__c ASC
                                            LIMIT 1  ] ; 
          if(lTimesheets.size()>0)                                            
            this.dtCurrentTS = lTimesheets[0].MondayDate__c ;     
          if(Moon_TimesheetDomain.TIMESHEET_STARTDATE_MANDATORY >this.dtCurrentTS  ){            
            this.dtCurrentTS = Moon_TimesheetDomain.TIMESHEET_STARTDATE_MANDATORY ;    

          }                                  
      } 
      return this.dtCurrentTS ; 

    }

    public static  Timesheet__c createTimesheet(User oUser,Date oMondayDate){

      String sExternalId = oMondayDate.year()+(''+oMondayDate.month()).leftPad(2,'0')+(''+oMondayDate.day()).leftPad(2,'0')+'-'+oUser.Id;
      return new Timesheet__c(MondayDate__c=oMondayDate,OwnerId=oUser.Id,ExternalId__c=sExternalId ) ; 
    }


}