force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Object used to assign an user to a stage of a project with a defined number of days to consume.</description>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{YYYY}-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimesheetEntry__c/TimesheetEntry__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TSE-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimesheetEntry__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <description>Each Assignment must be affected to an assignment</description>
    <label>Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>TimesheetEntries_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TimesheetEntry__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <description>Relationship between TSE and TS.</description>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>TimesheetEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Moon_TimesheetDomain_TEST.cls
@isTest
public class Moon_TimesheetDomain_TEST {

        @TestSetup
    public static void initTestData(){        
        TESTDataFactory.initSetupData() ; 
    }

    @isTest
    public static  void test_AllGetterStudentDomain_OK() {
        
        Moon_TimesheetDomain oTSDomain = new Moon_TimesheetDomain() ; 

        Test.startTest(); 
          List<Assignment__c> lAssignments = oTSDomain.getAssignements() ; 
          List<TimesheetEntry__c> lTSEntries = oTSDomain.getTimesheetEntries() ; 
          Timesheet__c oNewTimesheet = Moon_TimesheetDomain.createTimesheet([SELECT Id FROM User WHERE Id =:UserInfo.getUserId()][0],
                                                                Moon_TimesheetDomain.TIMESHEET_STARTDATE_MANDATORY+7) ; 
        Test.stopTest();

        System.assert(lAssignments.size()>0) ; 
        System.assert(lTSEntries.size()>0) ; 
        System.assert(oNewTimesheet!=null) ; 
    }

    @isTest
    public  static void test_AllGetterStudentDomain2_OK() {
        
        Moon_TimesheetDomain oTSDomain = new Moon_TimesheetDomain(Moon_TimesheetDomain.TIMESHEET_STARTDATE_MANDATORY) ; 

        Test.startTest(); 
          List<Assignment__c> lAssignments = oTSDomain.getAssignements() ; 
          List<TimesheetEntry__c> lTSEntries = oTSDomain.getTimesheetEntries() ; 
          Timesheet__c oNewTimesheet = Moon_TimesheetDomain.createTimesheet([SELECT Id FROM User WHERE Id =:UserInfo.getUserId()][0],
                                                                Moon_TimesheetDomain.TIMESHEET_STARTDATE_MANDATORY+7) ; 

        Test.stopTest();

        System.assert(lAssignments.size()>0) ; 
        System.assert(lTSEntries.size()>0) ; 
        System.assert(oNewTimesheet!=null) ;         
    }    
}