force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Object used to assign an user to a stage of a project with a defined number of days to consume.</description>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{YYYY}-{00000}</displayFormat>
        <label>Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimesheetEntry__c/TimesheetEntry__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <displayFormat>TSE-{YYYY}-{00000}</displayFormat>
        <label>Timesheet Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimesheetEntry__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <description>Each Assignment must be affected to an assignment</description>
    <label>Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>TimesheetEntries_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Moon_TimesheetsContainer_LC_TEST.cls
@isTest
public class Moon_TimesheetsContainer_LC_TEST {

    @TestSetup
    public static void initTestData(){        
        TESTDataFactory.initSetupData() ; 
    }

    @isTest
    public static  void test_TSContainerLC_OK() {
        
        String sToDeleteId = [SELECT Id FROM TimesheetEntry__c LIMIT 1][0].Id ;
        Test.startTest(); 
          Moon_TimesheetsContainer_LC.TimeSheetsDetailsWrapper oTSWrapper = Moon_TimesheetsContainer_LC.getTimeSheetsDetailsWrapper() ; 
          List<Assignment__c>  lAssignments = Moon_TimesheetsContainer_LC.getAssignements('2020-06-29') ; 
          Moon_TimesheetsContainer_LC.TimeSheetsDetailsWrapper oTSWrapperWithDate = Moon_TimesheetsContainer_LC.getTimeSheetsDetailsWrapper('2020-06-29') ; 
          Map<String,Object> oMapTS = Moon_TimesheetsContainer_LC.saveTimesheetsEntries(JSON.serialize(oTSWrapperWithDate.mapWeekTSEntries.values()[0]),
                                                  new List<String>{sToDeleteId},false) ;  

        Test.stopTest();

    }
   
}